In [2]:
import pandas as pd

In [13]:
EXAMPLE_FILE = '../../anaice/ILATM2_20110505_143158_smooth_nadir3seg_50pt.csv'
anaice = pd.read_csv(EXAMPLE_FILE,skiprows=9)

In [14]:
print('**********************************')
print('head: ')
print(anaice.head())
print('**********************************')
print('info of the dataframe: ')
print(anaice.info())
print('**********************************')
print('some more stats:  ')
print('**********************************')
max_values = anaice.max()
print('max values per column: ')
print(max_values)
print('**********************************')
min_values = anaice.min()
print('min values per column: ')
print(min_values)
print('**********************************')
mean_values = anaice.mean()
print('mean values per column: ')
print(mean_values)

**********************************
head:
   # UTC_Seconds_Of_Day   Latitude(deg)   Longitude(deg)  \
0              52303.75       76.070978       277.774945
1              52303.75       76.070351       277.779558
2              52303.75       76.069724       277.784170
3              52303.75       76.070038       277.781862
4              52304.00       76.070609       277.775223

    WGS84_Ellipsoid_Height(m)   South-to-North_Slope   West-to-East_Slope  \
0                      0.3341               0.000568            -0.000110
1                      0.2817              -0.000374            -0.000445
2                      0.2112               0.000494            -0.000290
3                      0.2473               0.001288            -0.000670
4                      0.3077               0.000589            -0.000253

    RMS_Fit(cm)   Number_Of_ATM_Measurments_Used  \
0          8.66                              325
1          7.09                              121
2          6.12                               86
3          5.14                               50
4          8.27                              421

    Number_Of_ATM_Measurements_Removed  \
0                                    2
1                                    4
2                                    1
3                                    0
4                                    1

    Distance_Of_Block_To_The_Right_Of_Aircraft(m)   Track_Identifier
0                                             213                  1
1                                              71                  2
2                                             -71                  3
3                                               0                  0
4                                             186                  1
**********************************
info of the dataframe:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5322 entries, 0 to 5321
Data columns (total 11 columns):
# UTC_Seconds_Of_Day                              5322 non-null float64
 Latitude(deg)                                    5322 non-null float64
 Longitude(deg)                                   5322 non-null float64
 WGS84_Ellipsoid_Height(m)                        5322 non-null float64
 South-to-North_Slope                             5322 non-null float64
 West-to-East_Slope                               5322 non-null float64
 RMS_Fit(cm)                                      5322 non-null float64
 Number_Of_ATM_Measurments_Used                   5322 non-null int64
 Number_Of_ATM_Measurements_Removed               5322 non-null int64
 Distance_Of_Block_To_The_Right_Of_Aircraft(m)    5322 non-null int64
 Track_Identifier                                 5322 non-null int64
dtypes: float64(7), int64(4)
memory usage: 457.4 KB
None
**********************************
some more stats:
**********************************
max values per column:
# UTC_Seconds_Of_Day                              52672.250000
 Latitude(deg)                                       76.070978
 Longitude(deg)                                     277.788260
 WGS84_Ellipsoid_Height(m)                          963.799700
 South-to-North_Slope                                 0.355410
 West-to-East_Slope                                   0.475454
 RMS_Fit(cm)                                        965.630000
 Number_Of_ATM_Measurments_Used                     703.000000
 Number_Of_ATM_Measurements_Removed                  70.000000
 Distance_Of_Block_To_The_Right_Of_Aircraft(m)      314.000000
 Track_Identifier                                     3.000000
dtype: float64
**********************************
min values per column:
# UTC_Seconds_Of_Day                              52303.750000
 Latitude(deg)                                       75.663349
 Longitude(deg)                                     277.401657
 WGS84_Ellipsoid_Height(m)                           -0.204500
 South-to-North_Slope                                -1.345193
 West-to-East_Slope                                  -1.130893
 RMS_Fit(cm)                                          3.580000
 Number_Of_ATM_Measurments_Used                      50.000000
 Number_Of_ATM_Measurements_Removed                   0.000000
 Distance_Of_Block_To_The_Right_Of_Aircraft(m)     -277.000000
 Track_Identifier                                     0.000000
dtype: float64
**********************************
mean values per column:
# UTC_Seconds_Of_Day                              52485.455045
 Latitude(deg)                                       75.875328
 Longitude(deg)                                     277.557462
 WGS84_Ellipsoid_Height(m)                          296.227986
 South-to-North_Slope                                -0.011144
 West-to-East_Slope                                   0.010746
 RMS_Fit(cm)                                         18.507046
 Number_Of_ATM_Measurments_Used                     385.563698
 Number_Of_ATM_Measurements_Removed                   4.593010
 Distance_Of_Block_To_The_Right_Of_Aircraft(m)      -10.387636
 Track_Identifier                                     1.507516
dtype: float64